version: '3.7'

networks:
  wp-network:

services:
  service_db:
    container_name: db
    build:
      context: ./mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - wp-network
    expose:
      - '3306'
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: wordpress

  service_wp:
    container_name: wp
    build:
      context: ./wordpress
    restart: always
    volumes:
      - ./site:/var/www/html
    depends_on:
      - service_db
    networks:
      - wp-network
    environment:
      WORDPRESS_DB_HOST: service_db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    volumes:
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

  service_http:
    container_name: nginx
    build:
      context: ./nginx
    restart: always
    ports:
      - 8080:80
    depends_on:
      - service_wp
      - service_db
    networks:
      - wp-network
    volumes:
      - ./site:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

volumes:
  site:
